### ISSUE TITLE
For those who can't get it to compile/work

### ISSUE THREAD

**Issue by aure2006** [Displee/RS3-model-viewer#7]
Edit: Updated for eclipse users.

1. Some error about "does not match the expected package".
Add src/main/java and src/main/resources as source folders.
2. "Getter cannot be resolved to a type".
Go here https://projectlombok.org/setup/eclipse and then add lombok.jar to your libraries.
3. "The import org.lwjgl.opengl cannot be resolved"
Download lwjgl-2.9.3.zip from the sourceforge link on this page http://legacy.lwjgl.org/download.php.html . Copy lwjgl-2.9.3/jar/lwjgl.jar from the zip file somewhere and add it to your libraries.
4. Some JavaFX exception when selecting a model.
In /src/main/java/com/displee/Constants.java, set ENABLE_TEXTURES to false.
In /src/main/java/com/displee/cache/ModelDefinition.java, comment out the whole for loop around line 493.

If you can't find the RS3 cache files, it's because NXT uses different cache files and you need to download the java client from here:
https://www.runescape.com/download/old-versions
You will also need to play the game with the java client so the cache gets downloaded.

**Comment by Displee** [comment]
There is a jar file in the 'lib' directory of the project which you have to import. This jar file contains the cache library with support for LZMA included.

**Comment by aure2006** [comment]
How do I import it?

**Comment by aure2006** [comment]
It was easier for me to just add the source instead of figuring out how to import it. Is it done with some command when compiling? Right now I'm just doing "mvn package".

**Comment by Displee** [comment]
No. You have to import the jar file into your project. How you would import it depends on what IDE you're using (if you use any, which I hope).

If you use Eclipse:
https://stackoverflow.com/questions/3280353/how-to-import-a-jar-in-eclipse

If you use Intellij:
https://stackoverflow.com/questions/1051640/correct-way-to-add-external-jars-lib-jar-to-an-intellij-idea-project
