### ISSUE TITLE
Cache files not found

### ISSUE THREAD

**Issue by Hyrtsi** [Displee/RS3-model-viewer#8]
Greetings,
I think the cache filenames have changed or something. Rs3 NXT client stores a bunch of these .jscache files. Your tool is looking for completely different files. Have I understood incorrectly?
Anyway good work, keep it up! Thanks for sharing this tool, I'm looking forward to getting it actually show some models :)

**Comment by Displee** [comment]
That's correct. Since NXT the cache files have changed. They're now SQL. I think you can view the .jscache files with SQLite.

The current cache library can only read the old cache files (.dat and .dat2) files.
